# Site settings
title: Left Hand Cypher
# email: your-email@domain.com
url: https://lefthandcypher.com
description: "Left Hand Cypher, LLC is a blockchain consulting firm specializing in protocol engineering, security research, and technical advising."
keywords: "blockchain, ethereum, solidity, smart contracts, security, protocol engineering, technical advising, consulting, security research, smart contract auditing, smart contract security, smart contract development, smart contract consulting, smart contract training, smart contract education"
skills: "Protocol Engineering - Security Research - Technical Advising "
meta_author: Left Hand Cypher, LLC

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Left Hand Cypher, LLC
  # location:
  # social: Around the Web
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/iamchrissmith
  - title: github
    url: http://github.com/iamchrissmith

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
